version: "3"
services: 
    app:
        container_name: commoditypedia
        restart: always
        build: .
        ports:
            - "80:8080"
        links:
            - mongo
        volumes: 
            - .:/usr/src/app
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
